version: "3.8"

services: 
    frontend:
        build: ./sites
        ports:
            - "3000:3000"
        restart: always
    
    db:
        image: mongo:latest
        ports: 
            - "4000:27017"
        volumes: 
            - ./db:/data/db
        restart: always
